version: '3'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    container_name: app
    restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: servirtoquewebco_wordpress_admin
      MYSQL_ROOT_PASSWORD: N1!nCcApc[E=
      MYSQL_PASSWORD: N1!nCcApc[E=
      MYSQL_DATABASE: servirtoquewebco_wordpress

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 100000000
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini